### ISSUE TITLE
Create dependent flows on the Organization page

### ISSUE THREAD

**Issue by juan-alencar** [tiki/dashboard#235]
### Deliverable

#219

### Description

Enhance the organization’s design by implementing the following workflows:

**Invite Members to the Organization:** The organization owner can invite users to the organization via email address.

**User Settings Menu:** Each user listed has a menu to manage their settings within the organization.

**Download Invoice:** Users can download the invoice PDF from the invoice history.

### Acceptance Criteria

- [ ] The organization owner can invite users to the organization via email address
- [ ] Each user listed has a menu to manage their settings within the organization.
- [ ] Users can download the invoice PDF from the invoice history.

**Comment by mike-audi** [comment]
@ricardobrg approved

**Comment by juan-alencar** [comment]
@MiroBenicio
